### ISSUE TITLE
Investigate issues with pub publish for version v1.2.14

### ISSUE THREAD

**Issue by ikurek** [ably/ably-flutter#400]
When @QuintinWillison tired to do `pub publish` to day the publish failed on Flutter 2.10.0 with this error:

```
Package validation found the following error:
* Your pubspec.yaml must not override non-dev dependencies.
  This ensures you test your package against the same versions of its dependencies
  that users will have when they use it.
Sorry, your package is missing a requirement and can't be published yet.
For more information, see: https://dart.dev/tools/pub/cmd/pub-lish.
pub finished with exit code 65
```

But the only dependencies that are overriden in `ably flutter` are test dependnecies, that are part of the `dev_dependencies`:

```
dependency_overrides:
  test_api: 0.4.9
  matcher: 0.12.11
``` 

There are reports about recent false positives with dependency override checks, f.e. https://github.com/dart-lang/pub/issues/3393, but we can probably solve this together with #396, by removing the overrides completely.

After update to latest version of Flutter (3.0.0) another issue occurs. Dependencies for `test_integration` package fail with an error like this:

```
* line 2, column 1 of test_integration/test_driver/runner.dart: This package does not have enum_to_string in the `dependencies` or `dev_dependencies` section of `pubspec.yaml`.
    ╷
  2 │ import 'package:enum_to_string/enum_to_string.dart';
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
```

Although they are properly declared in the `test_integration/pubspec.yaml` file:

```
dependencies:
  flutter:
    sdk: flutter

  ably_flutter:
    path: ".."

  args: ^2.3.1
  enum_to_string: ^2.0.1
  http: ^0.13.4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
```

We should investigate what causes these problems and fix them to enable pub.dev publishing.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1882) by [Unito](https://www.unito.io)
